apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  sources: 
  - repoURL: https://github.com/OmerSade1/Movie-app
    path: movie
    targetRevision: staging
    helm:
      valueFiles:
      - $values/environments/staging/values.yaml
  - repoURL: https://github.com/OmerSade1/argocd-gitops
    targetRevision: main
    ref: values
  destination: 
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true