frontend:
  image:  
    repository: 058264527754.dkr.ecr.us-east-1.amazonaws.com/movie_app_repo
    tag: frontend-test

backend:
  image: 
    repository: 058264527754.dkr.ecr.us-east-1.amazonaws.com/movie_app_repo
    tag: backend-test