frontend:
  image:
    replicas: 1
    repository: 058264527754.dkr.ecr.us-east-1.amazonaws.com/movie_app_repo
    tag: frontend-9b34751
    containerPort: 80
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1024Mi"
  ingress:
    host: "app.omsad.xyz"
    path: "/"

backend:
  image:
    replicas: 1
    repository: 058264527754.dkr.ecr.us-east-1.amazonaws.com/movie_app_repo
    tag: backend-9b34751
    containerPort: 5000
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1024Mi"
  ingress:
    host: "backend.omsad.xyz"
    path: "/movies"
